name: GO CI + Docker Build

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Go build
        run: go build ./...
      - name: Go test
        run: go test ./...
        
      - name: Install Azure CLI
        run: |
           curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      
      - name: Login to ACR (using admin credentials)
        run: |
            az acr login \
            --name ${{ secrets.ACR_NAME }} \
            --username ${{ secrets.ACR_USERNAME }} \
            --password ${{ secrets.ACR_PASSWORD }}
      
      - name: Build & push image using ACR Tasks
        run: |
          az acr build \
            --registry ${{ secrets.ACR_NAME }} \
            --image go-container-poc:latest \
            --file Dockerfile \
            --pull \
            --push \
            .
        

        
    
