name: GO CI + Docker Build

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Go build
        run: go build ./...
      - name: Go test
        run: go test ./...
        
      - name: Install Azure CLI
        run: |
           curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      
      - name: Login to ACR (using admin credentials)
        run: |
            az acr login \
            --name ${{ secrets.ACR_NAME }} \
            --username ${{ secrets.ACR_USERNAME }} \
            --password ${{ secrets.ACR_PASSWORD }}
      
      - name: Build Docker image
        run: |
          docker build \
            -t ${{ secrets.ACR_NAME }}.azurecr.io/go-container-poc:latest \
            -f Dockerfile \
            .
      
      - name: Push Docker image to ACR
        run: |
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/go-container-poc:latest
        

        
    
